[package]
edition = "2018"
name = "dodo"
version = "0.1.0"

[dependencies]
dodo-core = { path = "../dodo-core" }
dodo-assembler = { path = "../dodo-assembler" }
regex = { version = "1.5.4", default-features = false, features = ["std"] }
